_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
scenario_types: null
scenario_tokens:
  - 'd850d89f6c9853f7'
  - 'd4400226be545023'
  - 'dfb7236821255f7c'
  - 'deb75a0d5fe15fe3'
  - 'd685cf7d491f561e'
  - 'f5a79a8586975755'
  - 'd1be72658eed5030'
  - 'd5602809c55a5813'
  - 'df473df536d95d65'
  - 'eca0dc2510b352f4'
  - 'e212f3b5605f54a8'
  - 'e9ec20fe8cf255d6'
  - 'ec04ff5f69bb5acb'
  - 'f61d4a68faec5f56'
  - 'efd9ea2552f55c57'
  - 'd85b1236611d55dd'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: false
shuffle: false
