_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
scenario_types: null
scenario_tokens:
  - '2bec1c4a107d51be'
log_names: null
map_names: null
num_scenarios_per_type: 1
limit_total_scenarios: 1
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: false
shuffle: false
