_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
scenario_types: null
scenario_tokens:
  # left, distinct logs
  - '2bec1c4a107d51be'
  - '1796ce8fa03b58fb'
  - '459c92ce2dd95cb4'
  # right, distinct logs
  - '8bbc259ed68f506e'
  - '35acdd9464b85dd6'
  - '6a8322e0356b5616'
log_names: null
map_names: null
num_scenarios_per_type: 6
limit_total_scenarios: 6
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: false
