[pytest]
testpaths = tests
norecursedirs = nuplan-visualization Diffusion-Planner data exports outputs tmp checkpoints benchmarks mds plans training training_outputs validation_output validation_output2 exports_local
addopts = -ra

